### ISSUE TITLE
Is this repository being maintained?

### ISSUE THREAD

**Issue by cdimitroulas** [PageUpPeopleOrg/terraform-eventstore#2]
Hi there,

Not a real issue but I just wanted to ask whether there is any plan on maintaining this repository? It looks like there hasn't been any activity here for at least 2 years.

If not, do you know of any other `EventStore` terraform configurations that are out there which are a good place to look to understand how to setup an OSS cluster?

**Comment by mboudreau** [comment]
@cdimitroulas yeah, this isn't maintained anymore, we'll have to archive it.
